catalog/urls.py
from django.urls import path, include

from . import views

app_name = 'catalog'
urlpatterns = [
    # catalog/
    path('', views.product_list, name='product_list'),
    # catalog/1/item/1/
    path('<int:category_id>/item/<int:product_id>/', views.detail, name='detail'),
    # catalog/1/
    path('<int:category_id>/', views.sort_by_category, name='sort-by-category'),
    # catalog/order/
    path('order/', include('order.urls')),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path

from . import views

app_name = 'order'
urlpatterns = [
    # catalog/order/
    path('', views.view_cart, name='shopping-cart'),
    # catalog/order/item-added/product_id
    path('item-added/<int:product_id>/', views.add_to_cart, name='item-added'),
    # catalog/order/item-deleted/product_id
    path('item-deleted/<int:product_id>/', views.delete_from_cart, name='item-deleted'),
    # catalog/order/<ref_code>/
    path('<str:ref_code>/', views.checkout, name='checkout'),

]

catalog/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=60)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'categories'


class Manufacturer(models.Model):
    name = models.CharField(max_length=120)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=120)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    description = models.TextField()
    price = models.IntegerField()
    photo = models.ImageField(upload_to='products/', blank=True)

    def __str__(self):
        return self.name

order/models.py
from django.db import models
from catalog.models import Product

# Create your models here.

STATUS_CHOICES = (
    (1, ("Processing")),
    (2, ("Completed"))
)


class Order(models.Model):
    ref_code = models.CharField(max_length=60)
    customer_email = models.EmailField()
    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    date_ordered = models.DateTimeField(auto_now=True)
    products = models.ManyToManyField(Product, null=True, blank=True)
    total = models.DecimalField(max_digits=100, decimal_places=2, default=0.00)

    def __str__(self):
        return '{0} - {1}'.format(self.customer_email, self.ref_code)

order/forms.py
from django import forms


class CustomerForm(forms.Form):
    customer_email = forms.EmailField(label='Your email')

catalog/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from .models import Product, Category, Manufacturer


def product_list(request):
    products = Product.objects.all()
    categories = Category.objects.all()
    return render(request, 'product_list.html', {'products': products, 'categories': categories})


def detail(request, category_id, product_id):
    product = get_object_or_404(Product, pk=product_id)
    categories = Category.objects.all()
    return render(request, 'detail.html', {'category_id': category_id, 'product': product,
                                           'product_id': product_id, 'categories': categories})


def sort_by_category(request, category_id):
    categories = Category.objects.all()
    products = Product.objects.filter(category=category_id)
    return render(request, 'sort-by-category.html', {'products': products, 'categories': categories})


def sort_by_manufacturer(request, manufacturer_id):
    categories = Category.objects.all()
    product = get_list_or_404(Product, manufacturer=manufacturer_id)
    return render(request, 'sort-by-manufacturer.html', {'product': product, 'categories': categories})

order/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .extra_func import generate_ref_code
from catalog.models import Product, Category
from .models import Order
from .forms import CustomerForm
# Create your views here.


def view_cart(request):
    product_ids = request.session.get('cart', [])

    categories = Category.objects.all()

    products = Product.objects.filter(id__in=product_ids)
    total = sum(Product.objects.filter(id__in=product_ids).values_list('price', flat=True))
    form = CustomerForm

    if request.method == 'POST':
        form = CustomerForm(request.POST)
        if form.is_valid():
            ref_code = generate_ref_code()
            customer_email = form.cleaned_data['customer_email']
            order = Order.objects.create(ref_code=ref_code, customer_email=customer_email, total=float(total))

            order.products.set(products)

            request.session['cart'].clear()

            return redirect('/catalog/order/{}/'.format(ref_code))

    return render(request, 'shopping-cart.html', {'products': products, 'total': total, 'form': form,
                                                  'categories': categories})


def add_to_cart(request, product_id):
    cart = request.session.get('cart', [])

    if product_id not in cart:
        cart.append(product_id)
        request.session['cart'] = cart
        product = get_object_or_404(Product, pk=product_id)
    else:
        product = None

    return render(request, 'item-added.html', {'cart': cart, 'product': product})


def delete_from_cart(request, product_id):
    cart = request.session['cart']
    cart.remove(product_id)
    request.session['cart'] = cart
    product = get_object_or_404(Product, pk=product_id)
    return render(request, 'item-deleted.html', {'product': product})


def checkout(request, ref_code):
    order = get_object_or_404(Order, ref_code=ref_code)
    products = order.products.all()
    return render(request, 'checkout.html', {'products': products, 'ref_code': ref_code})

catalog/templates/base.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Welcome {% endblock %}</title>
    <link rel="stylesheet"  type="text/css" href="{% static 'css/style.css' %}">

</head>
<body>
<div class="nav-container">
	<nav>
  <ul>
  	  <li><a href="{% url 'catalog:product_list' %}">All Products</a></li>
      {% for category in categories %}
      <li><a href="{% url 'catalog:sort-by-category' category.id %}">{{ category.name }}</a></li>
      {% endfor %}
  </ul>
</nav>
    <div style="border: 3px solid green;"><a href="{% url 'catalog:order:shopping-cart' %}">My cart</a></div>
</div>
<div class="main-container">
    {% block content %}

    {% endblock %}
</div>
</body>
</html>

catalog/templates/detail.html
{% extends 'base.html' %}

{% block title %}
View detail on product
{% endblock %}
{% block content %}
<h2>{{ product.name }}</h2>
<br>
<img src="/catalog/img/{{ product.photo }}" alt="{{ product.name }}" width="300">
<br><p>{{ product.description|linebreaksbr }}</p>
<h3>{{ product.price }} &euro;</h3><button><h2><a href="/catalog/order/item-added/{{ product_id }}">Add to cart</a></h2></button>
{% endblock %}

catalog/templates/product_list.html
{% extends 'base.html' %}

{% block title %} Product List {% endblock %}
{% block content %}
    {% if products %}
    <ul>
    {% for product in products %}
        <li><a href="{% url 'catalog:detail' product.category.id product.id %}">
            <img src="/catalog/img/{{ product.photo }}" alt="{{ product.name }}" width="300"></a>
            <br>
            <a href="{% url 'catalog:detail' product.category.id product.id %}">{{ product.name }}</a>
            manufactured by {{ product.manufacturer.name }} <strong>{{ product.price }} &euro;</strong>
             -- {{ product.category.name }}<br></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No products are available.</p>
    {% endif %}
{% endblock %}

catalog/templates/sort-by-category.html
{% extends 'base.html' %}

{% block title %} All Products For Men {% endblock %}
{% block content %}
    {% if products %}
    <ul>
    {% for product in products %}
        <li><br><img src="/catalog/img/{{ product.photo }}" alt="{{ product.name }}" width="300"> <br>
            <a href="{% url 'catalog:detail' product.category.id product.id %}">{{ product.name }}</a>
            manufactured by {{ product.manufacturer.name }}  <strong>{{ product.price }} &euro;</strong><br></li>
    {% endfor %}
    </ul>
    {% else %}
        <p>No products are available.</p>
    {% endif %}
{% endblock %}

order/templates/checkout.html
{% extends 'base.html' %}

{% block title %}
Success!
{% endblock %}
{% block content %}
<h1>Thank you for your Order!
<br>Your order number: <strong>{{ ref_code }}</strong></h1>
<h2>You've ordered:</h2>
{% for product in products %}
<li>{{ product.name }}
    <img src="/catalog/img/{{ product.photo }}" alt="{{ product.name }}" width="300">
</li>
{% endfor %}
{% endblock %}

order/templates/item-added.html
{% extends 'base.html' %}

{% block title %}
You've added item to cart!
{% endblock %}
{% block content %}
{% if product == None %}
    <h2>You've already had this item in your cart</h2>
{% else %}
    <h2>The {{ product.name }} is now in your shopping cart:</h2>
    <br>
    <img src="/catalog/img/{{ product.photo }}" alt="{{ product.name }}" width="300">
    <br><p>{{ product.description|linebreaksbr }}</p>
    <h3>{{ product.price }} &euro;</h3>
{% endif %}
{% endblock %}

order/templates/item-deleted.html
{% extends 'base.html' %}

{% block title %}
You've deleted item from cart!
{% endblock %}
{% block content %}
<h2>The {{ product.name }} is no more in your shopping cart</h2>
{% endblock %}

order/templates/shopping-cart.html
{% extends 'base.html' %}

{% block title %}
Shopping Cart
{% endblock %}

{% block content %}
<h1>Here is your shopping cart so far</h1>


{% if products %}
    {% for product in products %}
        <li>
            <a href="{% url 'catalog:detail' product.category.id product.id %}">
                <img src="/catalog/img/{{ product.photo }}" alt="{{ product.name }}" width="300">
            </a>
            <br>
            <a href="{% url 'catalog:detail' product.category.id product.id %}">{{ product.name }}</a>
            manufactured by {{ product.manufacturer.name }}
            <strong>{{ product.price }} &euro;</strong>
            -- {{ product.category.name }}
            <br>
            <button><h2><a href="{% url 'catalog:order:item-deleted' product.id %}">Remove item from cart</a></h2></button>
        </li>
    {% endfor %}
<h2>Total: {{ total }} &euro;</h2>

<h3>To procceed to checkout give us your email:</h3>
<form action="/catalog/order/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
    </form>

{% else %}
    You don't have any items yet
{% endif %}

{% endblock %}